# https://fullstackopen.com/en/part12/basics_of_orchestration#exercises-12-17-12-19
services:
  mongo:
    image: mongo #https://hub.docker.com/ https://hub.docker.com/_/mongo
    ports:
      - 3456:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: the_database
    volumes:
      - ./todo-backend/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - ./todo-backend/mongo_data:/data/db
  redis:
    image: redis #https://hub.docker.com/_/redis
    ports:
      - 6378:6379
    # by default Redis does not persist the data. However, the persistence is easy to toggle on.
    command: ['redis-server', '--appendonly', 'yes'] # Overwrite the CMD
    volumes: # Declare the volume
      - ./redis_data:/data
  server:
    image: todo-backend-server-dev
    build:
      context: . # The context will pick this directory as the "build context"
      dockerfile: ./todo-backend/dev.Dockerfile # This will simply tell which dockerfile to read
    volumes:
      - ./todo-backend/app:/src/app
    environment:
      - MONGO_URL=mongodb://the_username:the_password@mongo:27017/the_database # @mongo matches the db service name "mongo"
      - REDIS_URL=redis://redis:6379 # //redis should match the service name "in our case redis". 6379 matches the application port.
    container_name: todo-backend-dev
    depends_on:
      - mongo
      - redis
  app:
    image: todo-front-dev
    build:
      context: . # The context will pick this directory as the "build context"
      dockerfile: ./todo-frontend/dev.Dockerfile # This will simply tell which dockerfile to read
    volumes:
      - ./todo-frontend:/usr/src/app # The path can be relative, so ./ is enough to say "the same location as the docker-compose.yml"
    environment:
      - VITE_BACKEND_URL=http://localhost:8080/api/
    container_name: todo-front-dev # This will name the container todo-front-dev
  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf:ro # ro means that the volume will be read-only.
    ports:
      - 8080:80
    container_name: reverse-proxy
    depends_on:
      - server
      - app # wait for the frontend container to be started
  #debug-helper:
    #image: busybox

# Run the app in development mode:
# docker compose -f docker-compose.dev.yml up

# Shut down the app in development mode:
# docker compose -f docker-compose.dev.yml down

# No need to define frontend and backend ports:
# You just need to expose the Nginx port (8080) to the host machine since the access to the backend and frontend is proxied to the right container port by Nginx.

# Because Nginx, frontend and backend are defined in the same Docker compose configuration, Docker puts those to the same Docker network and thanks to that, Nginx has direct access to frontend and backend containers ports.